[package]
name = "pulldown-cmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wai-bindgen-rust = "0.2.1"
original = {version ="0.9.2",package = "pulldown-cmark"}
